#!/usr/bin/env python3
"""
Utah-Kernel Packaging Utility (utah-pack)
-----------------------------------------
Ingests a compiled WebAssembly (.wasm) payload, injects it into the kernel
source, and invokes the Rust bootimage toolchain to forge a bootable image.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

# Bytes per line in the generated Rust array (keeps huge modules readable).
BYTES_PER_LINE = 16


def find_project_root() -> Path:
    """Locate the repository root (directory containing Cargo.toml)."""
    here = Path(__file__).resolve().parent
    if (here / "Cargo.toml").is_file():
        return here
    raise SystemExit("[FATAL ERROR] Run utah-pack.py from the Utah-Kernel repository root.")


def format_rust_byte_array(wasm_bytes: bytes) -> str:
    """Format WASM bytes as a Rust slice literal with wrapped lines."""
    if not wasm_bytes:
        return ""

    hex_items = [f"0x{b:02x}" for b in wasm_bytes]
    lines: list[str] = []
    for index in range(0, len(hex_items), BYTES_PER_LINE):
        chunk = ", ".join(hex_items[index : index + BYTES_PER_LINE])
        lines.append(f"        {chunk},")
    return "\n".join(lines)


def build_kernel_source(byte_array_body: str) -> str:
    """Return the full main.rs source with an embedded WASM payload."""
    return f"""#![no_std]
#![no_main]
#![feature(alloc_error_handler)]

extern crate alloc;

core::arch::global_asm!(include_str!("boot.asm"));

mod allocator;
mod chrono_scheduler;
mod delta_wave_patch;
mod ghost_daemon;
mod hfs;
mod kernel_config;
mod system_calls;
mod thermodynamic_virtualizer;
mod utah_os;
mod wasm_runtime;
mod zero_point_net;

use core::panic::PanicInfo;

const VIDEO_MEMORY_POINTER: *mut u8 = 0xb8000 as *mut u8;

#[no_mangle]
pub extern "C" fn _start() -> ! {{
    display_text_on_screen(b"Booting Utah-Kernel...");
    allocator::initialize_system_heap();
    utah_os::boot();

    // Injected WebAssembly payload (generated by utah-pack.py — do not edit by hand).
    let embedded_wasm_payload: &[u8] = &[
{byte_array_body}
    ];

    display_text_on_screen(b"Igniting WebAssembly Execution Engine...");
    wasm_runtime::run_web_assembly_program(embedded_wasm_payload);

    display_text_on_screen(b"Execution Complete. Halting CPU.");
    loop {{
        utah_os::service_idle();
    }}
}}

pub fn display_text_on_screen(text_to_print: &[u8]) {{
    let mut screen_position: isize = 0;
    for &character_byte in text_to_print {{
        unsafe {{
            *VIDEO_MEMORY_POINTER.offset(screen_position) = character_byte;
            *VIDEO_MEMORY_POINTER.offset(screen_position + 1) = 10;
        }}
        screen_position += 2;
    }}
}}

#[panic_handler]
fn handle_critical_system_crash(_crash_info: &PanicInfo) -> ! {{
    display_text_on_screen(b"CRITICAL KERNEL PANIC.");
    loop {{}}
}}
"""


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python utah-pack.py <path_to_payload.wasm>")
        sys.exit(1)

    wasm_path = Path(sys.argv[1]).expanduser().resolve()
    if not wasm_path.is_file():
        print(f"[FATAL ERROR] WebAssembly payload not found at: {wasm_path}")
        sys.exit(1)

    project_root = find_project_root()
    main_rs = project_root / "src" / "main.rs"

    print(f"[UTAH-PACK] Ingesting WebAssembly payload: {wasm_path}")
    wasm_bytes = wasm_path.read_bytes()
    print(f"[UTAH-PACK] Payload size: {len(wasm_bytes)} bytes")

    byte_array_body = format_rust_byte_array(wasm_bytes)
    kernel_source = build_kernel_source(byte_array_body)

    main_rs.write_text(kernel_source, encoding="utf-8", newline="\n")
    print(f"[UTAH-PACK] Wrote injected kernel source to {main_rs}")
    print("[UTAH-PACK] Initiating compiler (cargo bootimage)...")

    try:
        subprocess.run(
            ["cargo", "bootimage"],
            cwd=project_root,
            check=True,
        )
    except FileNotFoundError:
        print("[FATAL ERROR] 'cargo' not found. Install Rust via https://rustup.rs/")
        sys.exit(1)
    except subprocess.CalledProcessError:
        print(
            "[FATAL ERROR] Compilation failed. Install bootimage: cargo install bootimage"
        )
        sys.exit(1)

    profile = os.environ.get("UTAH_PACK_PROFILE", "debug")
    bin_name = f"bootimage-utah-kernel.bin"
    output_hint = project_root / "target" / "x86_64-unknown-none" / profile / bin_name

    print("\n[SUCCESS] Bootable OS image forged.")
    print(f"  Kernel binary: {output_hint}")
    print("  Emulate with:  cargo run")
    print("\nNote: src/main.rs was regenerated. Restore from version control if needed.")


if __name__ == "__main__":
    main()
