#![no_std]
#![no_main]
#![feature(alloc_error_handler)]

extern crate alloc;
extern crate glass_forge;

core::arch::global_asm!(include_str!("boot.asm"));

mod allocator;
mod chrono_scheduler;
mod delta_wave_patch;
mod ghost_daemon;
mod hfs;
mod kernel_config;
mod system_calls;
mod theme;
mod thermodynamic_virtualizer;
mod ui;
mod utah_os;
mod wasm_runtime;
mod zero_point_net;

use core::panic::PanicInfo;

const VIDEO_MEMORY_POINTER: *mut u8 = 0xb8000 as *mut u8;

#[no_mangle]
pub extern "C" fn _start() -> ! {
    display_text_on_screen(b"Booting Utah-Kernel...");
    allocator::initialize_system_heap();
    utah_os::boot();

    // Injected WebAssembly payload (generated by utah-pack.py — do not edit by hand).
    let embedded_wasm_payload: &[u8] = &[
        0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00,
    ];

    display_text_on_screen(b"Igniting WebAssembly Execution Engine...");
    wasm_runtime::run_web_assembly_program(embedded_wasm_payload);

    display_text_on_screen(b"Execution Complete. Halting CPU.");
    loop {
        utah_os::service_idle();
    }
}

pub fn display_text_on_screen(text_to_print: &[u8]) {
    let mut screen_position: isize = 0;
    for &character_byte in text_to_print {
        unsafe {
            *VIDEO_MEMORY_POINTER.offset(screen_position) = character_byte;
            *VIDEO_MEMORY_POINTER.offset(screen_position + 1) = 10;
        }
        screen_position += 2;
    }
}

#[panic_handler]
fn handle_critical_system_crash(_crash_info: &PanicInfo) -> ! {
    display_text_on_screen(b"CRITICAL KERNEL PANIC.");
    loop {}
}
